### ISSUE TITLE
behaviour of setlb! and setub!

### ISSUE THREAD

**Issue by tbulhoes** [atoptima/Coluna.jl#116]
Are the functions setlb! and setub! removing the master columns that do not satisfy the new bounds on subproblem variables? Preprocessing is calling these functions.

**Comment by guimarqu** [comment]
These methods only set the current lower and upper bounds of a variable in the formulation. If you want to remove a column, you have to set its coefficient to 0 in the matrix. Later, we will write a method that cleans the matrix and deletes unused variables.

**Comment by vitornesello** [comment]
We should think carefully about it. I not see an obvious solution.
We could:
 - Define a method `propagate!(::Formulation, ::FormulationChange)` that would be called when the user calls one of the functions that change the formulation, propagating the changes to other formulation which are impacted. This may be time consuming if not implemented carefully.
 - Leave it completely manual to the user, but it means that the user should know very well what it means to change the bounds of implicit variables in order to be coherent with himself. I don't like this option because it will be very hard for the contributors.

**Comment by guimarqu** [comment]
I think we should leave it manual. The user/algorithm knows what he does.

**Comment by guimarqu** [comment]
what do you think @rrsadykov ?

**Comment by rrsadykov** [comment]
Yes, I think removing master columns should be independent from setting bounds on subproblem variables. Master columns should be removed at the very end of preprocessing, once all subproblem variables bounds are determined.

**Comment by rrsadykov** [comment]
I plan to implement diving after I finish stabilization, we could then really test the preprocessing.

**Comment by guimarqu** [comment]
Conclusion : `setlb!` and `setub` change only bounds of variables.
