### ISSUE TITLE
no setrhs! in formulation

### ISSUE THREAD

**Issue by tbulhoes** [atoptima/Coluna.jl#117]
There is no setrhs function in formulation.jl. I think the idea is to communicate all changes in the formulation through the functions defined in this file, right? There is a setrhs function in constraint.jl, but I am not sure if it is the correct option to change the current rhs. I need to change it when preprocessing with a partial solution.

**Comment by guimarqu** [comment]
Methods defined in `formulation.jl` change the formulation and buffer the changes to avoid Coluna to recreate the formulation in the underlying solver each time it is called.
I guess we should have a method `setrhs!` because all modifications of the formulation should pass through the buffer.
You can write the method (and the tests) in a new branch and then submit a pull request. Otherwise, we will do it next week.

**Comment by tbulhoes** [comment]
Ok, I can do this.

**Comment by vitornesello** [comment]
can we close this? @guimarqu
