### ISSUE TITLE
UndefVarError: with_optimizer not defined

### ISSUE THREAD

**Issue by EduardoQueiroga** [atoptima/Coluna.jl#23]
The following error occurs when the GAP example is executed:

```
ERROR: LoadError: UndefVarError: with_optimizer not defined
Stacktrace:
 [1] model_sgap(::DataGap) at /home/eduardo/.julia/clones/13756470133505061496_full/examples/GeneralizedAssignment_SimpleColGen/model_sgap.jl:3
 [2] top-level scope at none:0
 [3] include at ./boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1038
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] include(::String) at ./client.jl:388
 [7] top-level scope at none:0
in expression starting at /home/eduardo/.julia/clones/13756470133505061496_full/examples/GeneralizedAssignment_SimpleColGen/run_sgap.jl:11
```
I am using Julia 1.0

**Comment by IssamT** [comment]
Hi @EduardoQueiroga. Indeed, that's why we didn't tag yet. We depend on jump 19 that I think will be released soon.

If you want to use Coluna now, you need to activate it's own environment (described in the manifest.toml):
1 - go to the folder of Coluna and run the Julia REPL
2- use ] to move to the Pkg REPL
3- `(Coluna) Pkg> activate .`
4- `(Coluna) Pkg> resolve`

If you still have the issue please post the result of 

`(Coluna) Pkg> status`

**Comment by EduardoQueiroga** [comment]
Hi @IssamT. I have followed your instructions and now it's working. I tried to run the instance 'gapC-10-100.txt' for the BAP example and the solution is apparently incorrect (value 1e06). Can you kindly inform what has been implemented so far (e.g. branch-and-price without cutting planes) and what are the perspectives for the Coluna.jl? 

Thank you

**Comment by IssamT** [comment]
The features implemented for now are the root node, branching on pure master variables, and the master ip restricted heuristic. The next step is to add branching on subproblem variables in the master.

**Comment by EduardoQueiroga** [comment]
I understand. Thank you @IssamT
