### ISSUE TITLE
Unable to get solver statistics

### ISSUE THREAD

**Issue by guilhemdupuis** [atoptima/Coluna.jl#384]
Hello,

Using Coluna for a benchmark on several instances, I would like to get some figures concerning the optimization process, like the computation time and the number of nodes in the branch and bound. Such information are printed out in the console, however I would like to store them in dedicated variables. I have tried `MOI.get(model, MOI.NodeCount())` but this results in the following error:
```ERROR: LoadError: ArgumentError: ModelLike of type Coluna.Optimizer does not support accessing the attribute MathOptInterface.NodeCount()```

How can I proceed? Thank you very much in advance.

**Comment by guimarqu** [comment]
Hi !

It's not implemented.

I wrote a dirty workaround in PR #385 so you can retrieve these statistics. You have to checkout the branch of the PR because I'll not merge this in master.

We have to devise a way to retrieve the benchmarks from the top algorithm. I put this on the TODO list of v0.4. This issue stays open until it's available.

Note that the total number of nodes may be different of what Coluna shows when you use strong branching.
