### ISSUE TITLE
Move code from eval to treat

### ISSUE THREAD

**Issue by tbulhoes** [atoptima/Coluna.jl#49]
The evaluation function contains a lot of things: setup, preprocessing, col gen and setdown. I am aware that a node may need to be evaluated twice because of strong branching, but I believe the current structure is not good. For the diving root node, for example, the evaluation does not need to be executed but then all these aforementioned things are skipped. I have modified the treat function a bit in branch "diving" as a first attempt to solve this problem.

**Comment by rrsadykov** [comment]
Dear Teobaldo,

Yes, this structure is quite rigid. However, it has the advantage that the treat node code is always the same, thus limiting the number of possible errors. Of course in future we can change things. 
Concerning diving, yes its root basically do nothing except generating children. But we always have possibility to define empty algorithms to limit the overhead.

I am not yet much familiar with the code, I will come back here after reviewing your suggestion.

**Comment by rrsadykov** [comment]
Dear Teobaldo,

I have looked at your changed. You moved problem setup, setdown, and preprocessing from evaluation to treat. I suppose you did this in order to be able to call preprocessing without calling the evalAlg.
I think this can be done more elegantly by defining empty evalAlg. Actually, we already do this in BapCod when we want to check (by preprocessing) whether the candidate column to fix makes the problem infeasible. For that, we create an auxiliary node with only preprocessing and with empty evalAlg. 

Actually, in the diving root, we should not call evalAlg, but we should not call preprocessing, problem setup and problem setdown neither. Preprocessing of the diving root does not make any sense as there is no local branching constraints and no local fixed solution neither. So, we skip everything (except generating child nodes) on purpose.

So I propose not to change the evaluation function. This function defines a clear division between the part of treat which modifies the problem (and the formulations behind) and the part which does not modify the problem. In the second part, if you want to modify the problem you need to create other nodes. This division has also a goal to prepare the code for the parallelisation: once evaluation function is finished, the problem and the formulations are "released" and can be used by other nodes in parallel while we perform heuristics and children generation in this node.

**Comment by tbulhoes** [comment]
Hello Ruslan,

For the diving root node, I just call setup, setdown and gen children algs (preprocessing and eval algs are empty). As I remember, the main reason for moving code from evaluation to treat was because the current code does not work if one skips setup and setdown for the diving root node. I am going to check this later today.

**Comment by rrsadykov** [comment]
Teobaldo, I do not see any need to call setup and setdown for the diving root. Why do you need that?

**Comment by tbulhoes** [comment]
Ruslan,
I agree that ideally it is not needed to run setup and setdown for the diving root node. However, here is why I did that:
   - in the current code, setdown is restoring default bounds of variables, so the bounds that have been changed by preprocessing in the root node are not passed to the diving root node if setup is skipped. 
  - prob_setup_info of node x equals the info of its parent if setdown is not executed for node x. This caused a bug related to the partial solution cost. This is fixed now, but I am not sure whether this choice is good. Why don't we copy prob_setup_info when generating the child node?

**Comment by rrsadykov** [comment]
Dear Teobaldo,

- setdown should not restore default bounds on variables, it should leave the formulation as it is. If the next node solved is the child, we should basically add the branching constraints and that's all, we should not restore bounds and then put the current bounds back again for the child. In BapCod setdown just resets the current solutions of the formulation and removes unused variables and constraints from the memory. So setdown should be corrected. I will try to do it next week. 
- It is totally ok the prob_setup_info stays the same for the diving root, as problem is not changed.

**Comment by vitornesello** [comment]
In setdown we are currently resetting the bounds of variables because I did not see a way to do the correct setup when the searched subtree changes. This happens because in setupinfo we store only the difference from the father, not the full state of the formulation. But I imagine this is not the best way to do it.

**Comment by rrsadykov** [comment]
Vitor,

In setdown, we should not reset the bounds, we should leave current bounds in place. Bound changes are computed in setup. Setup info contains the information about the bounds of original variables which are different from the default bounds. Based on this information, on default bounds and on current bounds, we can compute in setup all bounds we should change.

**Comment by vitornesello** [comment]
I understand, so this should be an easy thing to change. I will add an issue for that

**Comment by rrsadykov** [comment]
Dear Teobaldo and Vitor,

I think we should wait for now. Guillaume and François are doing a lot of changes in the data structure. Once it is ready, all algorithm will need to be updated.

**Comment by vitornesello** [comment]
No problem. I will be studying the changes in order be ready to work when I return.

**Comment by vitornesello** [comment]
We have re-designed this part of the code. This issue is no more.
