### ISSUE TITLE
Assessing dual solutions in a subproblem (BlockDecomposition)?

### ISSUE THREAD

**Issue by diHnguyen** [atoptima/Coluna.jl#608]
Could we access the dual solutions corresponding to the constraints assigned to a specific subproblem, as how it is done for reduced costs?

https://github.com/atoptima/Coluna.jl/blob/00b48ec371e67a82aa8c25669ab895e26786ff43/test/pricing_callback_tests.jl#L49-L53

When looking into the document of [BlockDecomposition.jl](https://github.com/realopt/BlockDecomposition.jl), under [callbacks.md](https://github.com/realopt/BlockDecomposition.jl/blob/master/docs/src/callbacks.md), it seems that we have the same operations:
``getspid()`` as ``BD.callback_spid()``
``getcurcost()`` as ``BD.callback_reduced_cost()``

There also exists ``getcurdual``, which I assume to retrieve the dual solutions. In that case, what would be the equivalent syntax in Coluna? Sorry if this isn't the case!

Thank you!! - DN

**Comment by guimarqu** [comment]
Hi,

When/why do you need the dual solution to the constraints of a specific subproblem?
I ask because when you do column generation, you usually end up solving the subproblem to optimality so I'm curious to know.

Yes, the BlockDecomposition package hosted in Realopt organization is not compatible with Coluna but pricing callback operations are the same.
I think `getcurdual` was to retrieve the dual cost of a master constraint. I'm not sure that Coluna has a similar method.
