### ISSUE TITLE
print subproblems and/or master

### ISSUE THREAD

**Issue by giommazz** [atoptima/Coluna.jl#757]
Would it be possible to have a function to to print pricing subproblems and/or the master?
It would be useful when debugging

**Comment by guimarqu** [comment]
@artalvpes Moving the content of the `book` branch in the column generation printer will close this issue.

**Comment by rrsadykov** [comment]
When printing `Reformulation` with `:user_only` flag, the master and pricing subproblem are printed with only user defined variables and constraints (artificial variables and columns are not shown): 

`print(IOContext(stdout, :user_only => true), reform)`

Later, another flag may be defined to show master columns (together with corresponding subproblem soutions) instead of representative variables.
