### ISSUE TITLE
Check how to deal with equalities when computing Benders cuts right-hand side

### ISSUE THREAD

**Issue by enjoyUrFruits** [atoptima/Coluna.jl#934]
In Benders ```_compute_cut_rhs_contrib``` we separate the contribution of classic linear inequalities from the contribution of the bounding constraints. The bounding contraints costs are given by ```dual_sol``` and their contribution depends on the sense of the bounding (UPPER, LOWER and LOWER_AND_UPPER). 

In the case of LOWER_AND_UPPER (i.e. equality) we have to check how to compute the good contribution. For the moment, given bounded variable ```constr: value <= x <= value```, the contribution equals ```value*cost(constr)```.

**Comment by guimarqu** [comment]
Equality is treated as two constraints: 'x <= value' & 'x >= value', and only one of them will be active. Consequently, the case `LOWER_AND_UPPER` should not happen. I think we should remove it from the `ActiveBound`.

Remove from the enum:
https://github.com/atoptima/Coluna.jl/blob/3420cd4e223e84cd7ba97a17a2e717e682eafa3e/src/MathProg/solutions.jl#L129-L129

Remove from the condition in Benders:
https://github.com/atoptima/Coluna.jl/blob/3420cd4e223e84cd7ba97a17a2e717e682eafa3e/src/Algorithm/benders/default.jl#L290-L290


Remove these 3 lines because they are not correct (see counterexample below but it can break some unit tests):
https://github.com/atoptima/Coluna.jl/blob/3420cd4e223e84cd7ba97a17a2e717e682eafa3e/src/MathProg/MOIinterface.jl#L326-L328

Remove from the test:
https://github.com/atoptima/Coluna.jl/blob/3420cd4e223e84cd7ba97a17a2e717e682eafa3e/test/unit/Benders/benders_cuts.jl#L169


counterexample:

```
MinSense + 1.0 y3 + 2.0 y1 + 1.0 y2 + 1.0 art1 + 1.0 art2 + 1.0 art3  
sp_c1 : + 1.0 y3 + 1.0 y1 + 2.0 y2 + 1.0 art1  >= 2.0 (BendSpPureConstrConstraintu1 | true)
sp_c2 : + 5.0 y1 - 1.0 y2 + 1.0 art2  >= 5.0 (BendSpTechnologicalConstrConstraintu2 | true)
sp_c3 : - 2.0 y3 + 1.0 art3  >= 3.0 (BendSpTechnologicalConstrConstraintu3 | true)
0.0 <= y3 <= 2.0 (Continuous | BendSpSepVar | true)
1.0 <= y1 <= 1.0 (Continuous | BendSpSepVar | true)
0.0 <= y2 <= 2.0 (Continuous | BendSpSepVar | true)
0.0 <= art1 <= Inf (Continuous | BendSpSecondStageArtVar | true)
0.0 <= art2 <= Inf (Continuous | BendSpSecondStageArtVar | true)
0.0 <= art3 <= Inf (Continuous | BendSpSecondStageArtVar | true)
```

Solutions:

```
primal = Primal solution
| y1 = 1.0
| y2 = 0.5
| art2 = 0.5
| art3 = 3.0
└ value = 6.00 

dual = Dual solution
| sp_c1 = 1.0
| sp_c2 = 1.0
| sp_c3 = 1.0
| y1 = -4.0 (UPPER)
| y3 = 2.0 (LOWER)
└ value = 6.00 
```
